### ISSUE TITLE
how to add object to render window

### ISSUE THREAD

**Issue by cekees** [jasongrout/pythreejs#15]
Is it  possible to add an object to a renderer that has  already been displayed?

**initial rendering of scene**
```
ball = Mesh(geometry=SphereGeometry(radius=1), material=LambertMaterial(color='red'), position=[2,1,0])
scene = Scene(children=[ball, AmbientLight(color=0x777777), make_text('Hello World!', height=.6)])
c = PerspectiveCamera(position=[0,5,5], up=[0,0,1], children=[DirectionalLight(color='white', 
                                                                             position=[3,5,1], 
                                                                             intensity=0.5)])
renderer = Renderer(camera=c, scene = scene, controls=[OrbitControls(controlling=c)])
ar = float(renderer.height)/(renderer.width)
renderer.width = 900
renderer.height = int(ar*800)
display(renderer)
```
**later addition of new object  into scene**
```
ball2 = Mesh(geometry=IcosahedronGeometry(radius=1), material=LambertMaterial(color='green'), position=[3,1,0])
scene.children.append(ball2)
```

If I just call  `display(renderer)` again, then the new object is in the scene, but it  doesn't get updated in the initial renderer widget.  @jdfreder, should I be calling something that comes from the widget interface instead to trigger a re-display of the first widget?

**Comment by jdfreder** [comment]
@cekees try 
`scene.children = scene.children + [ball2]`

Unless @jasongrout is making use of the eventful list type, and has implemented the appropriate syncing mechanisms, the List should be a Tuple, to force reassignment.

**Comment by cekees** [comment]
Great, that works if I reverse the order of the addition
```
scene.children = [ball2] + scene.children
```

**Comment by jdfreder** [comment]
Related to https://github.com/ipython/ipywidgets/issues/31
