### ISSUE TITLE
how to set lookAt vector

### ISSUE THREAD

**Issue by cekees** [jasongrout/pythreejs#16]
@jasongrout, I'm having trouble pointing the camera to the centroid of my scene, so I get clunky behavior from the orbital controls. Is  there a direct way I can set it? I believe it's the lookAt vector in three.js, but I don't see it exposed  by pythreejs.

**Comment by jasongrout** [comment]
Did you try the `look_at` method on the camera object?

**Comment by jasongrout** [comment]
Curiously, I'm not getting a look_at call to the camera to work.  It does seem to work with objects, however.

**Comment by jasongrout** [comment]
Okay, turns out the camera look_at function is overridden by the OrbitControls target.  So I just exposed the OrbitControls target value.  So do something like:

```
OrbitControls(target=(1,1,1), controlling = ...)
```
or if you instead do something like `c = OrbitControls(controlling=...)`, just update it with `c.target=(1,1,1)`.

Let me know if this works for you.

**Comment by jasongrout** [comment]
(You'll have to pull the latest master to get that commit, of course)

**Comment by cekees** [comment]
That works, thanks! I backported to a branch for IPython 3.1.0 and pushed it here: https://github.com/erdc-cm/pythreejs/tree/ipy3.1.0

**Comment by jasongrout** [comment]
Can you make a pull request?

**Comment by jasongrout** [comment]
@cekees - I think https://github.com/jasongrout/pythreejs/commit/f06441dd477ff00ec23dc691cb8105a4a8e3632f may make the master branch compatible with IPython 3.1.  If you have time, can you check to see if master now works with IPython 3.1?

**Comment by ivmi** [comment]
I am still not able to change camera angle from python. I have orbitcontroller and change its target position.
It works when orbitcontroller is not used.

Can anyone confirm it works or provide working example?
