### ISSUE TITLE
multiple Rendnerings side by side

### ISSUE THREAD

**Issue by oroszl** [jasongrout/pythreejs#23]
Is it possible to put two Rendnerings side by side ? I guess this is a widget question and I need to immerse myself in to widgets a bit more. But are there any caveats ? 
(I  guess this is one of the rookie ones..)

**Comment by jasongrout** [comment]
Try this...
```python
from IPython.html.widgets import HBox
...pythreejs code...
renderer = Renderer(...)
display(HBox([renderer, renderer]))
```

**Comment by oroszl** [comment]
Yep this is exactly what i needed (shows how rookie I am with the notebook.. )! A am closing this.
